{*******************************************************************************
  作者: dmzn@163.com 2014-03-07
  描述: 海康威视SDK常量定义
*******************************************************************************}
unit HKVConst;

interface

//------------------------------------------------------------------------------
//宏定义
const
  MAX_NAMELEN                = 16;    //设备登录用户名长度
  MAX_RIGHT                  = 32;    //设备支持的权限（1~12表示本地权限，13~32表示远程权限）
  NAME_LEN                   = 32;    //用户名长度
  PASSWD_LEN                 = 16;    //密码长度
  SERIALNO_LEN               = 48;    //序列号长度
  MACADDR_LEN                = 6;     //MAC地址长度
  MAX_ETHERNET               = 2;     //设备可配以太网络
  MAX_NETWORK_CARD           = 4;     //设备可配最大网卡数目
  MAX_BOND_NUM               = 2;     //设备可配BONDING网卡数
  PATHNAME_LEN               = 128;   //路径长度
  MAX_TIMESEGMENT_V30        = 8;     //V3.0以上版本支持的设备的最大时间段数
  MAX_TIMESEGMENT            = 4;     //V3.0以下版本支持的设备的最大时间段数
  MAX_SHELTERNUM             = 4;     //V3.0以下版本支持的设备的最大遮挡区域数
  MAX_DAYS                   = 7;     //每周的天数
  PHONENUMBER_LEN            = 32;    //PPPoE拨号号码最大长度
  MAX_DISKNUM_V30            = 33;    //V3.0以上版本支持的设备的最大硬盘数，最多33个硬盘(包括16个内置SATA硬盘、1个eSATA硬盘和16个NFS盘)
  MAX_DISKNUM                = 16;    //V3.0以下版本支持的设备的最大硬盘数
  MAX_DISKNUM_V10            = 8;     //1.2版本之前版本
  MAX_WINDOW_V30             = 32;    //V3.0以上版本支持的设备的本地显示最大播放窗口数
  MAX_WINDOW                 = 16;    //V3.0以下版本支持的设备的本地显示最大播放窗口数
  MAX_VGA_V30                = 4;     //V3.0以上版本支持的设备的最大可接VGA数
  MAX_VGA                    = 1;     //V3.0以下版本支持的设备的最大可接VGA数
  MAX_USERNUM_V30            = 32;    //V3.0以上版本支持的设备的最大用户数
  MAX_USERNUM                = 16;    //V3.0以下版本支持的设备的最大用户数
  MAX_EXCEPTIONNUM_V30       = 32;    //V3.0以上版本支持的设备的最大异常处理数
  MAX_EXCEPTIONNUM           = 16;    //V3.0以下版本支持的设备的最大异常处理数
  MAX_LINK                   = 6;     //V3.0以下版本支持的设备的单通道最大视频流连接数
  MAX_LINK_V30               = 128;   //V3.0以上版本支持的设备的单通道最大视频流连接数
  MAX_DECPOOLNUM             = 4;     //单路解码器每个解码通道最大可循环解码数
  MAX_DECNUM                 = 4;     //单路解码器的最大解码通道数（实际只有一个，其他三个保留）
  MAX_TRANSPARENTNUM         = 2;     //单路解码器可配置最大透明通道数
  MAX_CYCLE_CHAN             = 16;    //单路解码器最大轮巡通道数
  MAX_CYCLE_CHAN_V30         = 64;    //最大轮巡通道数（扩展）
  MAX_DIRNAME_LENGTH         = 80;    //最大目录长度
  MAX_WINDOWS                = 16;    //最大窗口数
  MAX_WINDOWS_V41            = 16;    //最大窗口数(v4.1版本SDK)
  MAX_STRINGNUM_V30          = 8;     //V3.0以上版本支持的设备的最大OSD字符行数
  MAX_STRINGNUM              = 4;     //V3.0以下版本支持的设备的最大OSD字符行数
  MAX_AUXOUT                 = 4;     //V3.0以下版本支持的设备的最大辅助输出数
  MAX_HD_GROUP               = 16;    //V3.0以上版本支持的设备的最大硬盘组数
  MAX_NFS_DISK               = 8;     //V3.0以下版本支持的设备的最大NFS硬盘数
  //IW_ESSID_MAX_SIZE          = 32;    //WIFI的SSID号长度
  IW_ENCODING_TOKEN_MAX      = 32;    //WIFI密钥最大字节数
  MAX_SERIAL_NUM             = 64;    //最多支持的透明通道路数
  MAX_DDNS_NUMS              = 10;    //V3.0以上版本支持的设备最大可配DDNS数
  MAX_DOMAIN_NAME            = 64;    //最大域名长度
  MAXPROGRESS                = 100;   //回放时的最大百分率
  MAX_SERIALNUM              = 2;     //设备支持的串口数：1-232，2-485
  CARDNUM_LEN                = 20;    //卡号长度
  MAX_VIDEOOUT_V30           = 4;     //V3.0以上版本支持的设备的视频输出数
  MAX_VIDEOOUT               = 2;     //V3.0以下版本支持的设备的视频输出数
  MAX_EMAIL_ADDR_LEN         = 48;    //最大EMAIL地址长度
  MAX_EMAIL_PWD_LEN          = 32;    //最大EMAIL密码长度
  MAX_PRESET_V30             = 256;   //V3.0以上版本支持的设备支持的云台预置点数
  MAX_TRACK_V30              = 256;   //V3.0以上版本支持的设备支持的云台轨迹数
  MAX_CRUISE_V30             = 256;   //V3.0以上版本支持的设备支持的云台巡航数
  MAX_PRESET                 = 128;   //V3.0以下版本支持的设备支持的云台预置点数
  MAX_TRACK                  = 128;   //V3.0以下版本支持的设备支持的云台轨迹数
  MAX_CRUISE                 = 128;   //V3.0以下版本支持的设备支持的云台巡航数
  CRUISE_MAX_PRESET_NUMS     = 32;    //一条巡航最多的巡航点
  MAX_SERIAL_PORT            = 8;     //V3.0以上版本支持的设备支持232串口数
  MAX_PREVIEW_MODE           = 8;     //设备支持最大预览模式数目 1画面,4画面,9画面,16画面.... 
  MAX_MATRIXOUT              = 16;    //最大模拟矩阵输出个数
  LOG_INFO_LEN               = 11840; //日志附加信息长度
  DESC_LEN                   = 16;    //云台描述字符串长度
  DESC_LEN_64                = 64;    //描述字符串长度
  PTZ_PROTOCOL_NUM           = 200;   //V3.0以上版本支持的设备最大支持的云台协议数
  MAX_AUDIO                  = 1;     //V3.0以下版本支持的设备的语音对讲通道数
  MAX_AUDIO_V30              = 2;     //V3.0以上版本支持的设备的语音对讲通道数
  MAX_CHANNUM                = 16;    //V3.0以下版本支持的设备的最大通道数
  MAX_ALARMIN                = 16;    //V3.0以下版本支持的设备的最大报警输入数
  MAX_ALARMOUT               = 4;     //V3.0以下版本支持的设备的最大报警输出数
  MAX_ANALOG_CHANNUM         = 32;    //最大32个模拟通道
  MAX_ANALOG_ALARMOUT        = 32;    //最大32路模拟报警输出
  MAX_ANALOG_ALARMIN         = 32;    //最大32路模拟报警输入
  MAX_IP_DEVICE              = 32;    //允许接入的最大IP设备数
  MAX_IP_DEVICE_V40          = 64;    //允许接入的最大IP设备数
  MAX_IP_CHANNEL             = 32;    //允许加入的最多IP通道数
  MAX_IP_ALARMIN             = 128;   //允许加入的最多报警输入数
  MAX_IP_ALARMOUT            = 64;    //允许加入的最多报警输出数
  MAX_IP_ALARMOUT_V40        = 4096;  //允许加入的最多报警输出数(扩展)
  MAX_CHANNUM_V30            = 64;    //(MAX_ANALOG_CHANNUM + MAX_IP_CHANNEL) 
  MAX_CHANNUM_V40            = 512;   //最大通道个数
  MAX_ALARMOUT_V30           = 96;    //(MAX_ANALOG_ALARMOUT + MAX_IP_ALARMOUT)
  MAX_ALARMOUT_V40           = 4128;  //(MAX_IP_ALARMOUT_V40 + MAX_ANALOG_ALARMOUT)
  MAX_ALARMIN_V30            = 160;   //(MAX_ANALOG_ALARMIN + MAX_IP_ALARMIN)
  MAX_MULTI_AREA_NUM         = 24;    //最大移动侦测区域个数
  MAX_RULE_NUM               = 8;     //最大规则条数
  MAX_RULE_NUM_4             = 4;     //最大规则数
  MAX_TIMESEGMENT_2          = 2;     //最大时间段数
  VCA_MAX_POLYGON_POINT_NUM  = 10;    //检测区域最多支持10个点的多边形
  MAX_TARGET_NUM             = 30;    //最大目标个数
  MAX_VCA_CHAN               = 16;    //最大智能通道数
  IW_ESSID_MAX_SIZE          = 32;    //SSID的长度
  WIFI_WEP_MAX_KEY_COUNT     = 4;     //最大密钥个数
  WIFI_WEP_MAX_KEY_LENGTH    = 33;    //最大密钥长度
  WIFI_WPA_PSK_MAX_KEY_LENGTH= 63;    //加密字符的最大长度
  WIFI_WPA_PSK_MIN_KEY_LENGTH= 8;     //加密字符的最小长度
  WIFI_MAX_AP_COUNT          = 20;    //无线AP的最大个数
  NET_DVR_MAX_DISPREGION     = 16;    //每个显示通道最多可以显示的窗口
  MAX_DECODECHANNUM          = 32;    //多路解码器最大解码通道数
  MAX_DISPCHANNUM            = 24;    //多路解码器最大显示通道数
  MAX_NET_DISK               = 16;    //最大网络硬盘数
  MAX_ATM_PROTOCOL_NUM       = 256;   //ATM最大协议数
  ATM_PROTOCOL_SORT          = 4;     //ATM协议段数
  ATM_DESC_LEN               = 32;    //ATM描述字符串长度
  MAX_ACTION_TYPE            = 12;    //ATM自定义协议叠加交易行为最大行为个数
  SEARCH_EVENT_INFO_LEN      = 300;   //事件信息长度
  MAX_MASK_REGION_NUM        = 4;     //最大屏蔽区域个数
  MAX_CALIB_PT               = 6;     //最大标定点个数
  MAX_RECT_NUM               = 6;     //最大矩形框个数
  MAX_RESOLUTIONNUM          = 64;    //支持的最大分辨率数目
  MAX_LOOPPLANNUM            = 16;    //最大计划切换组数
  DECODE_TIMESEGMENT         = 4;     //计划解码每天时间段数
  MAX_RECORD_FILE_NUM        = 20;    //一次操作文件( 备份、删除或刻录)的最大数目
  DESC_LEN_32                = 32;    //描述字长度
  MAX_NODE_NUM               = 256;   //节点个数
  MAX_ABILITYTYPE_NUM        = 12;    //最大能力项
  IPC_PROTOCOL_NUM           = 50;    //IPC协议最大个数
  MAX_SADP_NUM               = 256;   //搜索到设备最大数目
  SOFTWARE_VERSION_LEN       = 48;    //软件版本号长度
  MAX_LANERECT_NUM           = 5;     //最大车牌识别区域数
  MAX_LICENSE_LEN            = 16;    //车牌号最大长度
  MAX_FORTIFY_NUM            = 10;    //最大布防个数
  MAX_INTERVAL_NUM           = 4;     //最大时间间隔个数
  MAX_CHJC_NUM               = 3;     //最大车辆省份简称字符个数
  MAX_VL_NUM                 = 5;     //最大虚拟线圈个数
  MAX_DRIVECHAN_NUM          = 16;    //最大车道数
  MAX_COIL_NUM               = 3;     //最大线圈个数
  MAX_IOSPEED_GROUP_NUM      = 4;     //IO测速组个数
  MAX_IOOUT_NUM              = 4;     //最大IO输出口个数
  MAX_IOIN_NUM               = 8;     //最大IO输入口个数
  MAX_ITC_LANE_NUM           = 6;     //最大车道个数
  MAX_LIGHT_NUM              = 6;     //最大交通灯数
  MAX_VIDEO_DETECT_LIGHT_NUM = 12;    //最大视频检测信号灯个数
  MAX_VIDEO_INTERVAL_NUM     = 2;     //最大抓拍间隔数
  PICNAME_MAXITEM            = 2;     //图片命令最多元素个数
  MAX_LANEAREA_NUM           = 2;     //单车道最大区域个数
  ITC_MAX_POLYGON_POINT_NUM  = 20;    //检测区域最多支持20个点的多边形
  MAX_ITC_SERIALCHECK_NUM    = 8;     //串口校验类型个数
  MAX_LINE_SEG_NUM           = 8;     //最大样本线个数
  MAX_SAMPLE_NUM             = 5;     //最大样本个数
  MAX_SIGNALLIGHT_NUM        = 6;     //最大信号灯个数
  SUPPORT_PD_NUM             = 16;    //最大支持的物理磁盘个数
  SUPPORT_ARRAY_NUM          = 8;     //最大支持的阵列个数
  SUPPORT_VD_NUM             = 128;   //最大支持的虚拟磁盘个数
  LABEL_NAME_LEN             = 40;    //录像标签名称的长度
  LABEL_IDENTIFY_LEN         = 64;    //标签标识的长度
  MAX_DEL_LABEL_IDENTIFY     = 20;    //删除的最大标签标识个数
  MAX_PIC_EVENT_NUM          = 32;    //事件抓图的事件类型个数
  MAX_ALARMIN_CAPTURE        = 16;    //事件抓图报警输入个数
  CARDNUM_LEN_V30            = 40;    //卡号的长度
  PICTURE_NAME               = 64;    //图片名称的长度
  MAX_RECORD_PICTURE_NUM     = 50;    //最大备份图片张数
  CALIB_PT_NUM               = 4;     //智能交通事件标定个数
  MAX_REGION_NUM             = 8;     //区域列表最大数目
  MAX_LANE_NUM               = 8;     //最大车道数目
  MAX_AID_RULE               = 8;     //最大事件规则数目
  MAX_TPS_RULE               = 8;     //最大参数规则数目
  INQUEST_MESSAGE_LEN        = 44;    //审讯重点标记信息长度
  INQUEST_MAX_ROOM_NUM       = 2;     //最大审讯室个数
  MAX_RESUME_SEGMENT         = 2;     //支持同时恢复的片段数目
  MAX_ALARMHOST_SUBSYSTEM    = 32;    //网络报警主机子系统个数
  MAX_ALARMHOST_ALARMIN_NUM  = 512;   //网络报警主机最大报警输入口数
  MAX_ALARMHOST_ALARMOUT_NUM = 512;   //网络报警主机最大报警输出口数
  ALARMHOST_MAX_AUDIOOUT_NUM = 32;    //网络报警主机最大语音输出数
  ALARMHOST_MAX_ELECTROLOCK_NUM= 32;    //网络报警主机最大电锁数
  ALARMHOST_MAX_MOBILEGATE_NUM= 32;    //网络报警主机最大移动门数
  ALARMHOST_MAX_SIREN_NUM    = 8;     //网络报警主机最大警号数目
  MAX_DEVICE_PROTO_NUM       = 256;   //网络报警主机协议类型个数
  MAX_DEVICE_TYPE_NUM        = 256;   //网络报警主机设备类型个数
  MAX_CENTERNUM              = 4;     //网络报警主机支持的最大中心个数
  MAX_PHONE_NUM              = 32;    //拨号号码长度
  MAX_CONTENT_LEN            = 512;   //LED屏显内容最大长度
  LED_TIMER_NUM              = 3;     //LED开关机时间组数
  TIME_SEGMENT_A_DAY         = 48;    //时间段个数，一天24小时，半小时一个段
  MAX_SUPPORT_RES            = 32;    //最多支持的分辨率类型个数
  MAX_DISPNUM_V41            = 32;    //最大显示通道个数
  MAX_BIGSCREENNUM           = 100;   //最多大屏拼接子屏数
  MAX_WIN_COUNT              = 224;   //大屏支持最大的开窗个数
  MAX_WINDOWSMODE            = 12;    //最多支持的画面分割类型个数
  MAX_HUMAN_BIRTHDATE_LEN    = 10;    //最大出生年月长度
  MAX_HUMAN_PICTURE_NUM      = 10;    //最大图片数
  MAX_FACE_PIC_LEN           = 6144;  //最大人脸图片数据长度
  MAX_OSDCHAR_NUM            = 256;   //虚拟LED字符数
  STREAM_ID_LEN              = 32;    //流ID标识长度
  MAX_AUX_ALARM_NUM          = 8;     //最大辅助报警个数
  MAX_WIRELESS_ALARM_NUM     = 8;     //最大无线报警个数
  MAX_PRO_PATH               = 256;   //最大协议路径长度
  DEVICEID_LEN               = 32;    //设备ID号长度
  DVCS_DEVICEID_LEN          = 16;    //设备ID标识符长度
  MAX_ROIDETECT_NUM          = 8;     //ROI检测区域个数
  MAX_CABINET_COUNT          = 8;     //最大机柜个数
  ITS_MAX_DEVICE_NUM         = 32;    //最大设备个数
  MAX_ALERTLINE_NUM          = 8;     //最大警戒线条数
  MAX_INTRUSIONREGION_NUM    = 8;     //最大区域个数
  MAX_PARKING_NUM            = 4;     //一个通道最大车位个数
  MAX_PARKING_STATUS         = 8;     //车位状态个数
  MAX_ID_LEN                 = 48;    //编号最大长度
  MAX_ALARMREASON_LEN        = 8;     //报警类型描述最大长度
  MAX_SERVERID_LEN           = 64;    //最大服务器ID的长度
  MAX_SERVERDOMAIN_LEN       = 128;   //服务器域名最大长度
  MAX_AUTHENTICATEID_LEN     = 64;    //认证ID最大长度
  MAX_AUTHENTICATEPASSWD_LEN = 32;    //认证密码最大长度
  MAX_SERVERNAME_LEN         = 64;    //最大服务器用户名
  MAX_COMPRESSIONID_LEN      = 64;    //编码ID的最大长度
  MAX_SIPSERVER_ADDRESS_LEN  = 128;   //SIP服务器地址支持域名和IP地址

//------------------------------------------------------------------------------
//NET_DVR_GetLastError返回最后操作的错误码
const
  //网络通讯库错误码
  NET_DVR_NOERROR                   = 0;   //没有错误。
  NET_DVR_PASSWORD_ERROR            = 1;   //用户名密码错误。注册时输入的用户名或者密码错误。
  NET_DVR_NOENOUGHPRI               = 2;   //权限不足。一般和通道相关，例如有预览通道1权限，无预览通道2权限，即有预览权限但不完全，预览通道2返回此错误。
  NET_DVR_NOINIT                    = 3;   //SDK未初始化。
  NET_DVR_CHANNEL_ERROR             = 4;   //通道号错误。设备没有对应的通道号。
  NET_DVR_OVER_MAXLINK              = 5;   //设备总的连接数超过最大。
  NET_DVR_VERSIONNOMATCH            = 6;   //版本不匹配。SDK和设备的版本不匹配。
  NET_DVR_NETWORK_FAIL_CONNECT      = 7;   //连接设备失败。设备不在线或网络原因引起的连接超时等。
  NET_DVR_NETWORK_SEND_ERROR        = 8;   //向设备发送失败。
  NET_DVR_NETWORK_RECV_ERROR        = 9;   //从设备接收数据失败。
  NET_DVR_NETWORK_RECV_TIMEOUT      = 10;  //从设备接收数据超时。
  NET_DVR_NETWORK_ERRORDATA         = 11;  //传送的数据有误。发送给设备或者从设备接收到的数据错误，如远程参数配置时输入设备不支持的值。
  NET_DVR_ORDER_ERROR               = 12;  //调用次序错误。
  NET_DVR_OPERNOPERMIT              = 13;  //无此权限。用户对某个功能模块的权限，例如无预览权限用户预览返回此错误。
  NET_DVR_COMMANDTIMEOUT            = 14;  //设备命令执行超时。
  NET_DVR_ERRORSERIALPORT           = 15;  //串口号错误。指定的设备串口号不存在。
  NET_DVR_ERRORALARMPORT            = 16;  //报警端口错误。指定的设备报警输入或者输出端口不存在。
  NET_DVR_PARAMETER_ERROR           = 17;  //参数错误。SDK接口中给入的输入或输出参数为空，或者参数格式或值不符合要求。
  NET_DVR_CHAN_EXCEPTION            = 18;  //设备通道处于错误状态
  NET_DVR_NODISK                    = 19;  //设备无硬盘。当设备无硬盘时，对设备的录像文件、硬盘配置等操作失败。
  NET_DVR_ERRORDISKNUM              = 20;  //硬盘号错误。当对设备进行硬盘管理操作时，指定的硬盘号不存在时返回该错误。
  NET_DVR_DISK_FULL                 = 21;  //设备硬盘满。
  NET_DVR_DISK_ERROR                = 22;  //设备硬盘出错
  NET_DVR_NOSUPPORT                 = 23;  //设备不支持。
  NET_DVR_BUSY                      = 24;  //设备忙。
  NET_DVR_MODIFY_FAIL               = 25;  //设备修改不成功。
  NET_DVR_PASSWORD_FORMAT_ERROR     = 26;  //密码输入格式不正确
  NET_DVR_DISK_FORMATING            = 27;  //硬盘正在格式化，不能启动操作。
  NET_DVR_DVRNORESOURCE             = 28;  //设备资源不足。
  NET_DVR_DVROPRATEFAILED           = 29;  //设备操作失败。
  NET_DVR_OPENHOSTSOUND_FAIL        = 30;  //语音对讲、语音广播操作中采集本地音频或打开音频输出失败。
  NET_DVR_DVRVOICEOPENED            = 31;  //设备语音对讲被占用。
  NET_DVR_TIMEINPUTERROR            = 32;  //时间输入不正确。
  NET_DVR_NOSPECFILE                = 33;  //回放时设备没有指定的文件。
  NET_DVR_CREATEFILE_ERROR          = 34;  //创建文件出错。本地录像、保存图片、获取配置文件和远程下载录像时创建文件失败。
  NET_DVR_FILEOPENFAIL              = 35;  //打开文件出错。设置配置文件、设备升级、上传审讯文件时打开文件失败。
  NET_DVR_OPERNOTFINISH             = 36;  //上次的操作还没有完成。
  NET_DVR_GETPLAYTIMEFAIL           = 37;  //获取当前播放的时间出错。
  NET_DVR_PLAYFAIL                  = 38;  //播放出错。
  NET_DVR_FILEFORMAT_ERROR          = 39;  //文件格式不正确。
  NET_DVR_DIR_ERROR                 = 40;  //路径错误
  NET_DVR_ALLOC_RESOURCE_ERROR      = 41;  //SDK资源分配错误。
  NET_DVR_AUDIO_MODE_ERROR          = 42;  //声卡模式错误。当前打开声音播放模式与实际设置的模式不符出错。
  NET_DVR_NOENOUGH_BUF              = 43;  //缓冲区太小。接收设备数据的缓冲区或存放图片缓冲区不足。
  NET_DVR_CREATESOCKET_ERROR        = 44;  //创建SOCKET出错。
  NET_DVR_SETSOCKET_ERROR           = 45;  //设置SOCKET出错。
  NET_DVR_MAX_NUM                   = 46;  //个数达到最大。分配的注册连接数、预览连接数超过SDK支持的最大数。
  NET_DVR_USERNOTEXIST              = 47;  //用户不存在。注册的用户ID已注销或不可用。
  NET_DVR_WRITEFLASHERROR           = 48;  //写FLASH出错。设备升级时写FLASH失败。
  NET_DVR_UPGRADEFAIL               = 49;  //设备升级失败。网络或升级文件语言不匹配等原因升级失败。
  NET_DVR_CARDHAVEINIT              = 50;  //解码卡已经初始化过。
  NET_DVR_PLAYERFAILED              = 51;  //调用播放库中某个函数失败。
  NET_DVR_MAX_USERNUM               = 52;  //登录设备的用户数达到最大。
  NET_DVR_GETLOCALIPANDMACFAIL      = 53;  //获得本地PC的IP地址或物理地址失败。
  NET_DVR_NOENCODEING               = 54;  //设备该通道没有启动编码。
  NET_DVR_IPMISMATCH                = 55;  //IP地址不匹配。
  NET_DVR_MACMISMATCH               = 56;  //MAC地址不匹配。
  NET_DVR_UPGRADELANGMISMATCH       = 57;  //升级文件语言不匹配。
  NET_DVR_MAX_PLAYERPORT            = 58;  //播放器路数达到最大。
  NET_DVR_NOSPACEBACKUP             = 59;  //备份设备中没有足够空间进行备份。
  NET_DVR_NODEVICEBACKUP            = 60;  //没有找到指定的备份设备。
  NET_DVR_PICTURE_BITS_ERROR        = 61;  //图像素位数不符，限24色。
  NET_DVR_PICTURE_DIMENSION_ERROR   = 62;  //图片高*宽超限，限128*256。
  NET_DVR_PICTURE_SIZ_ERROR         = 63;  //图片大小超限，限100K。
  NET_DVR_LOADPLAYERSDKFAILED       = 64;  //载入当前目录下Player Sdk出错。
  NET_DVR_LOADPLAYERSDKPROC_ERROR   = 65;  //找不到Player Sdk中某个函数入口。
  NET_DVR_LOADDSSDKFAILED           = 66;  //载入当前目录下DSsdk出错。
  NET_DVR_LOADDSSDKPROC_ERROR       = 67;  //找不到DsSdk中某个函数入口。
  NET_DVR_DSSDK_ERROR               = 68;  //调用硬解码库DsSdk中某个函数失败。
  NET_DVR_VOICEMONOPOLIZE           = 69;  //声卡被独占。
  NET_DVR_JOINMULTICASTFAILED       = 70;  //加入多播组失败。
  NET_DVR_CREATEDIR_ERROR           = 71;  //建立日志文件目录失败。
  NET_DVR_BINDSOCKET_ERROR          = 72;  //绑定套接字失败。
  NET_DVR_SOCKETCLOSE_ERROR         = 73;  //socket连接中断，此错误通常是由于连接中断或目的地不可达。
  NET_DVR_USERID_ISUSING            = 74;  //注销时用户ID正在进行某操作。
  NET_DVR_SOCKETLISTEN_ERROR        = 75;  //监听失败。
  NET_DVR_PROGRAM_EXCEPTION         = 76;  //程序异常。
  NET_DVR_WRITEFILE_FAILED          = 77;  //写文件失败。本地录像、远程下载录像、下载图片等操作时写文件失败。
  NET_DVR_FORMAT_READONLY           = 78;  //禁止格式化只读硬盘。
  NET_DVR_WITHSAMEUSERNAME          = 79;  //远程用户配置结构中存在相同的用户名。
  NET_DVR_DEVICETYPE_ERROR          = 80;  //导入参数时设备型号不匹配。
  NET_DVR_LANGUAGE_ERROR            = 81;  //导入参数时语言不匹配。
  NET_DVR_PARAVERSION_ERROR         = 82;  //导入参数时软件版本不匹配。
  NET_DVR_IPCHAN_NOTALIVE           = 83;  //预览时外接IP通道不在线。
  NET_DVR_RTSP_SDK_ERROR            = 84;  //加载标准协议通讯库StreamTransClient失败。
  NET_DVR_CONVERT_SDK_ERROR         = 85;  //加载转封装库失败。
  NET_DVR_IPC_COUNT_OVERFLOW        = 86;  //超出最大的IP接入通道数。
  NET_DVR_MAX_ADD_NUM               = 87;  //添加录像标签或者其他操作超出最多支持的个数。
  NET_DVR_PARAMMODE_ERROR           = 88;  //图像增强仪，参数模式错误（用于硬件设置时，客户端进行软件设置时错误值）。
  NET_DVR_CODESPITTER_OFFLINE       = 89;  //码分器不在线。
  NET_DVR_BACKUP_COPYING            = 90;  //设备正在备份。
  NET_DVR_CHAN_NOTSUPPORT           = 91;  //通道不支持该操作。
  NET_DVR_CALLINEINVALID            = 92;  //高度线位置太集中或长度线不够倾斜。
  NET_DVR_CALCANCELCONFLICT         = 93;  //取消标定冲突，如果设置了规则及全局的实际大小尺寸过滤。
  NET_DVR_CALPOINTOUTRANGE          = 94;  //标定点超出范围。
  NET_DVR_FILTERRECTINVALID         = 95;  //尺寸过滤器不符合要求。
  NET_DVR_DDNS_DEVOFFLINE           = 96;  //设备没有注册到ddns上。
  NET_DVR_DDNS_INTER_ERROR          = 97;  //DDNS 服务器内部错误。
  NET_DVR_FUNCTION_NOT_SUPPORT_OS   = 98;  //此功能不支持该操作系统。
  NET_DVR_DEC_CHAN_REBIND           = 99;  //解码通道绑定显示输出次数受限。
  NET_DVR_INTERCOM_SDK_ERROR        = 100; //加载当前目录下的语音对讲库失败。
  NET_DVR_NO_CURRENT_UPDATEFILE     = 101; //没有正确的升级包。
  NET_DVR_ALIAS_DUPLICATE           = 150; //别名重复（HiDDNS的配置）

  //阵列错误码
  NET_DVR_NAME_NOT_ONLY             = 200; //名称已存在。
  NET_DVR_OVER_MAX_ARRAY            = 201; //阵列达到上限。
  NET_DVR_OVER_MAX_VD               = 202; //虚拟磁盘达到上限。
  NET_DVR_VD_SLOT_EXCEED            = 203; //虚拟磁盘槽位已满。
  NET_DVR_PD_STATUS_INVALID         = 204; //重建阵列所需物理磁盘状态错误。
  NET_DVR_PD_BE_DEDICATE_SPARE      = 205; //重建阵列所需物理磁盘为指定热备。
  NET_DVR_PD_NOT_FREE               = 206; //重建阵列所需物理磁盘非空闲。
  NET_DVR_CANNOT_MIG2NEWMODE        = 207; //不能从当前的阵列类型迁移到新的阵列类型。
  NET_DVR_MIG_PAUSE                 = 208; //迁移操作已暂停。
  NET_DVR_MIG_CANCEL                = 209; //正在执行的迁移操作已取消。
  NET_DVR_EXIST_VD                  = 210; //阵列上存在虚拟磁盘，无法删除阵列。
  NET_DVR_TARGET_IN_LD_FUNCTIONAL   = 211; //对象物理磁盘为虚拟磁盘组成部分且工作正常。
  NET_DVR_HD_IS_ASSIGNED_ALREADY    = 212; //指定的物理磁盘被分配为虚拟磁盘。
  NET_DVR_INVALID_HD_COUNT          = 213; //物理磁盘数量与指定的RAID等级不匹配。
  NET_DVR_LD_IS_FUNCTIONAL          = 214; //阵列正常，无法重建。
  NET_DVR_BGA_RUNNING               = 215; //存在正在执行的后台任务。
  NET_DVR_LD_NO_ATAPI               = 216; //无法用ATAPI盘创建虚拟磁盘。
  NET_DVR_MIGRATION_NOT_NEED        = 217; //阵列无需迁移。
  NET_DVR_HD_TYPE_MISMATCH          = 218; //物理磁盘不属于同意类型。
  NET_DVR_NO_LD_IN_DG               = 219; //无虚拟磁盘，无法进行此项操作。
  NET_DVR_NO_ROOM_FOR_SPARE         = 220; //磁盘空间过小，无法被指定为热备盘。
  NET_DVR_SPARE_IS_IN_MULTI_DG      = 221; //磁盘已被分配为某阵列热备盘。
  NET_DVR_DG_HAS_MISSING_PD         = 222; //阵列缺少盘。
  NET_DVR_NAME_EMPTY                = 223; //名称为空。
  NET_DVR_INPUT_PARAM               = 224; //输入参数有误。
  NET_DVR_PD_NOT_AVAILABLE          = 225; //物理磁盘不可用。
  NET_DVR_ARRAY_NOT_AVAILABLE       = 226; //阵列不可用。
  NET_DVR_PD_COUNT                  = 227; //物理磁盘数不正确。
  NET_DVR_VD_SMALL                  = 228; //虚拟磁盘太小。
  NET_DVR_NO_EXIST                  = 229; //不存在。
  NET_DVR_NOT_SUPPORT               = 230; //不支持该操作。
  NET_DVR_NOT_FUNCTIONAL            = 231; //阵列状态不是正常状态。
  NET_DVR_DEV_NODE_NOT_FOUND        = 232; //虚拟磁盘设备节点不存在。
  NET_DVR_SLOT_EXCEED               = 233; //槽位达到上限。
  NET_DVR_NO_VD_IN_ARRAY            = 234; //阵列上不存在虚拟磁盘。
  NET_DVR_VD_SLOT_INVALID           = 235; //虚拟磁盘槽位无效。
  NET_DVR_PD_NO_ENOUGH_SPACE        = 236; //所需物理磁盘空间不足。
  NET_DVR_ARRAY_NONFUNCTION         = 237; //只有处于正常状态的阵列才能进行迁移。
  NET_DVR_ARRAY_NO_ENOUGH_SPACE     = 238; //阵列空间不足。
  NET_DVR_STOPPING_SCANNING_ARRAY   = 239; //正在执行安全拔盘或重新扫描。
  NET_DVR_NOT_SUPPORT_16T           = 240; //不支持创建大于16T的阵列。

  //智能设备错误码
  NET_DVR_ID_ERROR                  = 300; //配置ID不合理。
  NET_DVR_POLYGON_ERROR             = 301; //多边形不符合要求。
  NET_DVR_RULE_PARAM_ERROR          = 302; //规则参数不合理。
  NET_DVR_RULE_CFG_CONFLICT         = 303; //配置信息冲突。
  NET_DVR_CALIBRATE_NOT_READY       = 304; //当前没有标定信息。
  NET_DVR_CAMERA_DATA_ERROR         = 305; //摄像机参数不合理。
  NET_DVR_CALIBRATE_DATA_UNFIT      = 306; //长度不够倾斜，不利于标定。
  NET_DVR_CALIBRATE_DATA_CONFILICT  = 307; //标定出错，以为所有点共线或者位置太集中。
  NET_DVR_CALIBRATE_CALC_FAIL       = 308; //摄像机标定参数值计算失败。
  NET_DVR_CALIBRATE_LINE_OUT_RECT   = 309; //输入的样本标定线超出了样本外接矩形框。
  NET_DVR_ENTER_RULE_NOT_READY      = 310; //没有设置进入区域
  NET_DVR_AID_RULE_NO_INCLUDE_LANE  = 311; //交通事件规则中没有包括车道（特值拥堵和逆行）
  NET_DVR_LANE_NOT_READY            = 312; //当前没有设置车道
  NET_DVR_RULE_INCLUDE_TWO_WAY      = 313; //事件规则中包含2种不同方向
  NET_DVR_LANE_TPS_RULE_CONFLICT    = 314; //车道和数据规则冲突
  NET_DVR_NOT_SUPPORT_EVENT_TYPE    = 315; //不支持的事件类型
  NET_DVR_LANE_NO_WAY               = 316; //车道没有方向
  NET_DVR_SIZE_FILTER_ERROR         = 317; //尺寸过滤框不合理
  NET_DVR_LIB_FFL_NO_FACE           = 318; //特征点定位时输入的图像没有人脸
  NET_DVR_LIB_FFL_IMG_TOO_SMALL     = 319; //特征点定位时输入的图像太小
  NET_DVR_LIB_FD_IMG_NO_FACE        = 320; //单张图像人脸检测时输入的图像没有人脸
  NET_DVR_LIB_FACE_TOO_SMALL        = 321; //建模时人脸太小
  NET_DVR_LIB_FACE_QUALITY_TOO_BAD  = 322; //建模时人脸图像质量太差
  NET_DVR_KEY_PARAM_ERR             = 323; //高级参数设置错误
  NET_DVR_CALIBRATE_DATA_ERR        = 324; //标定样本数目错误，或数据值错误，或样本点超出地平线
  NET_DVR_CALIBRATE_DISABLE_FAIL    = 325; //所配置规则不允许取消标定
  NET_DVR_VCA_LIB_FD_SCALE_OUTRANGE = 326; //最大过滤框的宽高最小值超过最小过滤框的宽高最大值两倍以上
  NET_DVR_LIB_FD_REGION_TOO_LARGE   = 327; //当前检测区域范围过大。检测区最大为图像的2/3
  NET_DVR_TRIAL_OVERDUE             = 328; //试用版评估期已结束
  NET_DVR_CONFIG_FILE_CONFLICT      = 329; //设备类型与配置文件冲突（加密狗类型与现有分析仪配置不符错误码提示）
  NET_DVR_FR_FPL_FAIL               = 330; //人脸特征点定位失败
  NET_DVR_FR_IQA_FAIL               = 331; //人脸评分失败
  NET_DVR_FR_FEM_FAIL               = 332; //人脸特征提取失败
  NET_DVR_FPL_DT_CONF_TOO_LOW       = 333; //特征点定位时人脸检测置信度过低
  NET_DVR_FPL_CONF_TOO_LOW          = 334; //特征点定位置信度过低
  NET_DVR_E_DATA_SIZE               = 335; //数据长度不匹配
  NET_DVR_FR_MODEL_VERSION_ERR      = 336; //人脸模型数据中的模型版本错误
  NET_DVR_FR_FD_FAIL                = 337; //识别库中人脸检测失败
  NET_DVR_FA_NORMALIZE_ERR          = 338; //人脸归一化出错
  NET_DVR_DOG_PUSTREAM_NOT_MATCH    = 339; //加密狗与前端取流设备类型不匹配
  NET_DVR_DEV_PUSTREAM_NOT_MATCH    = 340; //前端取流设备版本不匹配
  NET_DVR_PUSTREAM_ALREADY_EXISTS   = 341; //设备的其他通道已经添加过该前端设备
  NET_DVR_SEARCH_CONNECT_FAILED     = 342; //连接检索服务器失败
  NET_DVR_INSUFFICIENT_DISK_SPACE   = 343; //可存储的硬盘空间不足
  NET_DVR_DATABASE_CONNECTION_FAILED= 344; //数据库连接失败
  NET_DVR_DATABASE_ADM_PW_ERROR     = 345; //数据库用户名、密码错误
  NET_DVR_DECODE_YUV                = 346; //解码失败

  //其他错误码
  NET_DVR_DEV_NET_OVERFLOW          = 800; //网络流量超过设备能力上限
  NET_DVR_STATUS_RECORDFILE_WRITING_NOT_LOCK= 801; //录像文件在录像，无法被锁定
  NET_DVR_STATUS_CANT_FORMAT_LITTLE_DISK= 802; //由于硬盘太小无法格式化

  //N+1功能错误码
  NET_SDK_ERR_REMOTE_DISCONNEC      = 803; //远端无法连接
  NET_SDK_ERR_RD_ADD_RD             = 804; //备机不能添加备机
  NET_SDK_ERR_BACKUP_DISK_EXCEPT    = 805; //备份盘异常
  NET_SDK_ERR_RD_LIMIT              = 806; //备机数已达上限
  NET_SDK_ERR_ADDED_RD_IS_WD        = 807; //添加的备机是工作机
  NET_SDK_ERR_ADD_ORDER_WRONG       = 808; //添加顺序出错，比如没有被工作机添加为备机，就添加工作机
  NET_SDK_ERR_WD_ADD_WD             = 809; //工作机不能添加工作机
  NET_SDK_ERR_WD_SERVICE_EXCETP     = 810; //工作机CVR服务异常
  NET_SDK_ERR_RD_SERVICE_EXCETP     = 811; //备机CVR服务异常
  NET_SDK_ERR_ADDED_WD_IS_RD        = 812; //添加的工作机是备机
  NET_SDK_ERR_PERFORMANCE_LIMIT     = 813; //性能达到上限
  NET_SDK_ERR_ADDED_DEVICE_EXIST    = 814; //添加的设备已经存在

  //审讯机错误码   
  NET_SDK_ERR_INQUEST_RESUMING      = 815; //审讯恢复中。
  NET_SDK_ERR_RECORD_BACKUPING      = 816; //审讯备份中。
  NET_SDK_ERR_DISK_PLAYING          = 817; //光盘回放中。
  NET_SDK_ERR_INQUEST_STARTED       = 818; //审讯已开启。
  NET_SDK_ERR_LOCAL_OPERATING       = 819; //本地操作进行中。
  NET_SDK_ERR_INQUEST_NOT_START     = 820; //审讯未开启。

  //多屏控制器错误码   
  NET_ERROR_SCENE_USING             = 717; //场景正在使用。
  NET_ERR_WINCHAN_IDX               = 901; //开窗通道号错误。
  NET_ERR_WIN_LAYER                 = 902; //窗口层数错误，单个屏幕上最多覆盖的窗口层数。
  NET_ERR_WIN_BLK_NUM               = 903; //窗口的块数错误，单个窗口可覆盖的屏幕个数。
  NET_ERR_OUTPUT_RESOLUTION         = 904; //输出分辨率错误。
  NET_ERR_LAYOUT                    = 905; //场景号错误。
  NET_ERR_INPUT_RESOLUTION          = 906; //输入分辨率不支持。
  NET_ERR_SUBDEVICE_OFFLINE         = 907; //子设备不在线。
  NET_ERR_NO_DECODE_CHAN            = 908; //没有空闲解码通道。
  NET_ERR_MAX_WINDOW_ABILITY        = 909; //开窗能力上限，分布式多屏控制器中解码子设备能力上限或者显示处理器能力上限导致。
  NET_ERR_ORDER_ERROR               = 910; //调用顺序有误。
  NET_ERR_PLAYING_PLAN              = 911; //正在执行预案。
  NET_ERR_DECODER_USED              = 912; //解码板正在使用。
  NET_ERR_OUTPUT_BOARD_DATA_OVERFLOW= 913; //输出板数据量超限。
  NET_ERR_SAME_USER_NAME            = 914; //用户名相同。
  NET_ERR_INVALID_USER_NAME         = 915; //无效用户名。
  NET_ERR_MATRIX_USING              = 916; //输入矩阵正在使用。
  NET_ERR_DIFFERENT_CHAN_TYPE       = 917; //通道类型不同（矩阵输出通道和控制器的输入为不同的类型）。
  NET_ERR_INPUT_CHAN_BINDED         = 918; //输入通道已经被其他矩阵绑定。
  NET_ERR_BINDED_OUTPUT_CHAN_OVERFLOW= 919; //正在使用的矩阵输出通道个数超过矩阵与控制器绑定的通道个数。
  NET_ERR_MAX_SIGNAL_NUM            = 920; //输入信号源个数达到上限。
  NET_ERR_INPUT_CHAN_USING          = 921; //输入通道正在使用。
  NET_ERR_MANAGER_LOGON             = 922; //管理员已经登陆，操作失败。
  NET_ERR_USERALREADY_LOGON         = 923; //该用户已经登陆，操作失败。
  NET_ERR_LAYOUT_INIT               = 924; //场景正在初始化，操作失败。
  NET_ERR_BASEMAP_SIZE_NOT_MATCH    = 925; //底图大小不符。
  NET_ERR_WINDOW_OPERATING          = 926; //窗口正在执行其他操作，本次操作失败。
  NET_ERR_SIGNAL_UPLIMIT            = 927; //信号源开窗个数达到上限。

  //解码器错误码
  NET_ERR_MAX_WIN_OVERLAP           = 951; //达到最大窗口重叠数
  NET_ERR_STREAMID_CHAN_BOTH_VALID  = 952; //stream ID和通道号同时有效
  NET_ERR_NO_ZERO_CHAN              = 953; //设备无零通道
  NEED_RECONNECT                    = 955; //需要重定向（转码子系统使用）
  NET_ERR_NO_STREAM_ID              = 956; //流ID不存在
  NET_DVR_TRANS_NOT_START           = 957; //转码未启动
  NET_ERR_MAXNUM_STREAM_ID          = 958; //流ID数达到上限
  NET_ERR_WORKMODE_MISMATCH         = 959; //工作模式不匹配
  NET_ERR_MODE_IS_USING             = 960; //已工作在当前模式
  NET_ERR_DEV_PROGRESSING           = 961; //设备正在处理中
  NET_ERR_PASSIVE_TRANSCODING       = 962; //正在被动转码

  //能力集错误码
  XML_ABILITY_NOTSUPPORT            = 1000;//不支持能力节点获取。
  XML_ANALYZE_NOENOUGH_BUF          = 1001;//输出内存不足。
  XML_ANALYZE_FIND_LOCALXML_ERROR   = 1002;//无法找到对应的本地xml。
  XML_ANALYZE_LOAD_LOCALXML_ERROR   = 1003;//加载本地xml出错。
  XML_NANLYZE_DVR_DATA_FORMAT_ERROR = 1004;//设备能力数据格式错误。
  XML_ANALYZE_TYPE_ERROR            = 1005;//能力集类型错误。
  XML_ANALYZE_XML_NODE_ERROR        = 1006;//XML能力节点格式错误。
  XML_INPUT_PARAM_ERROR             = 1007;//输入的能力XML节点值错误。
  XML_VERSION_MISMATCH              = 1008;//XML版本不匹配。

  //报警设备错误码
  NET_ERR_SEARCHING_MODULE          = 1201;//正在搜索外接模块。
  NET_ERR_REGISTERING_MODULE        = 1202;//正在注册外接模块。
  NET_ERR_GETTING_ZONES             = 1203;//正在获取防区参数。
  NET_ERR_GETTING_TRIGGERS          = 1204;//正在获取触发器。
  NET_ERR_ARMED_STATUS              = 1205;//系统处于布防状态。
  NET_ERR_PROGRAM_MODE_STATUS       = 1206;//系统处于编程模式。
  NET_ERR_WALK_TEST_MODE_STATUS     = 1207;//系统处于步测模式。
  NET_ERR_BYPASS_STATUS             = 1208;//旁路状态。
  NET_ERR_DISABLED_MODULE_STATUS    = 1209;//功能未使能。
  NET_ERR_NOT_SUPPORT_OPERATE_ZONE  = 1210;//防区不支持该操作。
  NET_ERR_NOT_SUPPORT_MOD_MODULE_ADDR= 1211;//模块地址不能被修改。
  NET_ERR_UNREGISTERED_MODULE       = 1212;//模块未注册。
  NET_ERR_PUBLIC_SUBSYSTEM_ASSOCIATE_SELF= 1213;//公共子系统关联自身。
  NET_ERR_EXCEEDS_ASSOCIATE_SUBSYSTEM_NUM= 1214;//超过公共子系统最大关联个数。
  NET_ERR_BE_ASSOCIATED_BY_PUBLIC_SUBSYSTEM= 1215;//子系统被其他公共子系统关联。
  NET_ERR_ZONE_FAULT_STATUS         = 1216;//防区处于故障状态。
  NET_ERR_SAME_EVENT_TYPE           = 1217;//事件触发报警输出开启和事件触发报警输出关闭中有相同事件类型。
  NET_ERR_ZONE_ALARM_STATUS         = 1218;//防区处于报警状态。
  NET_ERR_EXPANSION_BUS_SHORT_CIRCUIT= 1219;//扩展总线短路。

  //抓拍机错误码
  NET_DVR_ERR_LANENUM_EXCEED        = 1400;//车道数超出能力。
  NET_DVR_ERR_PRAREA_EXCEED         = 1401;//牌识区域过大。
  NET_DVR_ERR_LIGHT_PARAM           = 1402;//信号灯接入参数错误。
  NET_DVR_ERR_LANE_LINE_INVALID     = 1403;//车道线配置错误。
  NET_DVR_ERR_STOP_LINE_INVALID     = 1404;//停止线配置错误。
  NET_DVR_ERR_LEFTORRIGHT_LINE_INVALID= 1405;//左/右转分界线配置错误。
  NET_DVR_ERR_LANE_NO_REPEAT        = 1406;//叠加车道号重复。
  NET_DVR_ERR_PRAREA_INVALID        = 1407;//牌识多边形不符合要求。
  NET_DVR_ERR_LIGHT_NUM_EXCEED      = 1408;//视频检测交通灯信号灯数目超出最大值。
  NET_DVR_ERR_SUBLIGHT_NUM_INVALID  = 1409;//视频检测交通灯信号灯子灯数目不合法
  NET_DVR_ERR_LIGHT_AREASIZE_INVALID= 1410;//视频检测交通灯输入信号灯框大小不合法。
  NET_DVR_ERR_LIGHT_COLOR_INVALID   = 1411;//视频检测交通灯输入信号灯颜色不合法。
  NET_DVR_ERR_LIGHT_DIRECTION_INVALID= 1412;//视频检测交通灯输入灯方向属性不合法。
  //VQD错误码
  NET_ERR_VQD_TIME_CONFLICT         = 1500;//VQD诊断时间段冲突。
  NET_ERR_VQD_PLAN_NO_EXIST         = 1501;//VQD诊断计划不存在。
  NET_ERR_VQD_CHAN_NO_EXIST         = 1502;//VQD监控点不存在。
  NET_ERR_VQD_CHAN_MAX              = 1503;//VQD计划数已达上限。
  NET_ERR_VQD_TASK_MAX              = 1504;//VQD任务数已达上限。

  //RTSP通讯库错误码
  NET_DVR_RTSP_ERROR_NOENOUGHPRI    = 401; //认证失败：服务器返回401时，转成这个错误码
  NET_DVR_RTSP_ERROR_ALLOC_RESOURCE = 402; //分配资源失败
  NET_DVR_RTSP_ERROR_PARAMETER      = 403; //参数错误
  NET_DVR_RTSP_ERROR_NO_URL         = 404; //指定的URL地址不存在：服务器返回404时，转成这个错误码，例如请求不可用的通道号预览、请求不支持子码流的通道预览
  NET_DVR_RTSP_ERROR_FORCE_STOP     = 406; //用户中途强行退出
  NET_DVR_RTSP_GETPORTFAILED        = 407; //获取RTSP端口错误
  NET_DVR_RTSP_DESCRIBERROR         = 410; //RTSP DECRIBE交互错误
  NET_DVR_RTSP_DESCRIBESENDTIMEOUT  = 411; //RTSP DECRIBE发送超时
  NET_DVR_RTSP_DESCRIBESENDERROR    = 412; //RTSP DECRIBE发送失败
  NET_DVR_RTSP_DESCRIBERECVTIMEOUT  = 413; //RTSP DECRIBE接收超时
  NET_DVR_RTSP_DESCRIBERECVDATALOST = 414; //RTSP DECRIBE接收数据错误
  NET_DVR_RTSP_DESCRIBERECVERROR    = 415; //RTSP DECRIBE接收失败
  NET_DVR_RTSP_DESCRIBESERVERERR    = 416; //RTSP DECRIBE 服务器返回错误状态。例如服务器返回400，可能是不支持子码流
  NET_DVR_RTSP_SETUPERROR           = 420; //RTSP SETUP交互错误，一般是服务器返回的码流地址无法连接上，或者被服务器拒绝。（老版本的SDK可能返回错误号419，为同样的错误原因）
  NET_DVR_RTSP_SETUPSENDTIMEOUT     = 421; //RTSP SETUP发送超时
  NET_DVR_RTSP_SETUPSENDERROR       = 422; //RTSP SETUP发送错误
  NET_DVR_RTSP_SETUPRECVTIMEOUT     = 423; //RTSP SETUP接收超时
  NET_DVR_RTSP_SETUPRECVDATALOST    = 424; //RTSP SETUP接收数据错误
  NET_DVR_RTSP_SETUPRECVERROR       = 425; //RTSP SETUP接收失败
  NET_DVR_RTSP_OVER_MAX_CHAN        = 426; //超过服务器最大连接数，或者服务器资源不足，服务器返回453时，转成这个错误码
  NET_DVR_RTSP_SETUPSERVERERR       = 427; //RTSP SETUP 服务器返回错误状态
  NET_DVR_RTSP_PLAYERROR            = 430; //RTSP PLAY交互错误
  NET_DVR_RTSP_PLAYSENDTIMEOUT      = 431; //RTSP PLAY发送超时
  NET_DVR_RTSP_PLAYSENDERROR        = 432; //RTSP PLAY发送错误
  NET_DVR_RTSP_PLAYRECVTIMEOUT      = 433; //RTSP PLAT接收超时
  NET_DVR_RTSP_PLAYRECVDATALOST     = 434; //RTSP PLAY接收数据错误
  NET_DVR_RTSP_PLAYRECVERROR        = 435; //RTSP PLAY接收失败
  NET_DVR_RTSP_PLAYSERVERERR        = 436; //RTSP PLAY 服务器返回错误状态
  NET_DVR_RTSP_TEARDOWNERROR        = 440; //RTSP TEARDOWN交互错误
  NET_DVR_RTSP_TEARDOWNSENDTIMEOUT  = 441; //RTSP TEARDOWN发送超时
  NET_DVR_RTSP_TEARDOWNSENDERROR    = 442; //RTSP TEARDOWN发送错误
  NET_DVR_RTSP_TEARDOWNRECVTIMEOUT  = 443; //RTSP TEARDOWN接收超时
  NET_DVR_RTSP_TEARDOWNRECVDATALOST = 444; //RTSP TEARDOWN接收数据错误
  NET_DVR_RTSP_TEARDOWNRECVERROR    = 445; //RTSP TEARDOWN接收失败
  NET_DVR_RTSP_TEARDOWNSERVERERR    = 446; //RTSP TEARDOWN 服务器返回错误状态

  //软解码库错误码
  NET_PLAYM4_NOERROR                = 500; //没有错误
  NET_PLAYM4_PARA_OVER              = 501; //输入参数非法
  NET_PLAYM4_ORDER_ERROR            = 502; //调用顺序不对
  NET_PLAYM4_TIMER_ERROR            = 503; //多媒体时钟设置失败
  NET_PLAYM4_DEC_VIDEO_ERROR        = 504; //视频解码失败
  NET_PLAYM4_DEC_AUDIO_ERROR        = 505; //音频解码失败
  NET_PLAYM4_ALLOC_MEMORY_ERROR     = 506; //分配内存失败
  NET_PLAYM4_OPEN_FILE_ERROR        = 507; //文件操作失败
  NET_PLAYM4_CREATE_OBJ_ERROR       = 508; //创建线程事件等失败
  NET_PLAYM4_CREATE_DDRAW_ERROR     = 509; //创建directDraw失败
  NET_PLAYM4_CREATE_OFFSCREEN_ERROR = 510; //创建后端缓存失败
  NET_PLAYM4_BUF_OVER               = 511; //缓冲区满，输入流失败
  NET_PLAYM4_CREATE_SOUND_ERROR     = 512; //创建音频设备失败
  NET_PLAYM4_SET_VOLUME_ERROR       = 513; //设置音量失败
  NET_PLAYM4_SUPPORT_FILE_ONLY      = 514; //只能在播放文件时才能使用此接口
  NET_PLAYM4_SUPPORT_STREAM_ONLY    = 515; //只能在播放流时才能使用此接口
  NET_PLAYM4_SYS_NOT_SUPPORT        = 516; //系统不支持，解码器只能工作在Pentium 3以上
  NET_PLAYM4_FILEHEADER_UNKNOWN     = 517; //没有文件头
  NET_PLAYM4_VERSION_INCORRECT      = 518; //解码器和编码器版本不对应
  NET_PALYM4_INIT_DECODER_ERROR     = 519; //初始化解码器失败
  NET_PLAYM4_CHECK_FILE_ERROR       = 520; //文件太短或码流无法识别
  NET_PLAYM4_INIT_TIMER_ERROR       = 521; //初始化多媒体时钟失败
  NET_PLAYM4_BLT_ERROR              = 522; //位拷贝失败
  NET_PLAYM4_UPDATE_ERROR           = 523; //显示overlay失败
  NET_PLAYM4_OPEN_FILE_ERROR_MULTI  = 524; //打开混合流文件失败
  NET_PLAYM4_OPEN_FILE_ERROR_VIDEO  = 525; //打开视频流文件失败
  NET_PLAYM4_JPEG_COMPRESS_ERROR    = 526; //JPEG压缩错误
  NET_PLAYM4_EXTRACT_NOT_SUPPORT    = 527; //不支持该文件版本.
  NET_PLAYM4_EXTRACT_DATA_ERROR     = 528; //提取文件数据失败

  //语音对讲库错误码
  NET_AUDIOINTERCOM_OK              = 600; //没有错误
  NET_AUDIOINTECOM_ERR_NOTSUPORT    = 601; //不支持
  NET_AUDIOINTECOM_ERR_ALLOC_MEMERY = 602; //内存申请错误
  NET_AUDIOINTECOM_ERR_PARAMETER    = 603; //参数错误
  NET_AUDIOINTECOM_ERR_CALL_ORDER   = 604; //调用次序错误
  NET_AUDIOINTECOM_ERR_FIND_DEVICE  = 605; //未发现设备
  NET_AUDIOINTECOM_ERR_OPEN_DEVICE  = 606; //不能打开设备
  NET_AUDIOINTECOM_ERR_NO_CONTEXT   = 607; //设备上下文出错
  NET_AUDIOINTECOM_ERR_NO_WAVFILE   = 608; //WAV文件出错
  NET_AUDIOINTECOM_ERR_INVALID_TYPE = 609; //无效的WAV参数类型
  NET_AUDIOINTECOM_ERR_ENCODE_FAIL  = 610; //编码失败
  NET_AUDIOINTECOM_ERR_DECODE_FAIL  = 611; //解码失败
  NET_AUDIOINTECOM_ERR_NO_PLAYBACK  = 612; //播放失败
  NET_AUDIOINTECOM_ERR_DENOISE_FAIL = 613; //降噪失败
  NET_AUDIOINTECOM_ERR_UNKOWN       = 619; //未知错误

  //Qos流控库错误码
  NET_QOS_ERR_SCHEDPARAMS_BAD_MINIMUM_INTERVAL= 678; //预设的最小间隔错误.
  NET_QOS_ERR_SCHEDPARAMS_BAD_FRACTION= 679; //预设分数错误
  NET_QOS_ERR_SCHEDPARAMS_INVALID_BANDWIDTH= 680; //预设的带宽值无效
  NET_QOS_ERR_PACKET_TOO_BIG        = 687; //数据包太大
  NET_QOS_ERR_PACKET_LENGTH         = 688; //数据包长度错误
  NET_QOS_ERR_PACKET_VERSION        = 689; //数据包版本错误
  NET_QOS_ERR_PACKET_UNKNOW         = 690; //未知数据包
  NET_QOS_ERR_OUTOFMEM              = 695; //内存不足
  NET_QOS_ERR_LIB_NOT_INITIALIZED   = 696; //Lib库没有初始化
  NET_QOS_ERR_SESSION_NOT_FOUND     = 697; //没有找到会话
  NET_QOS_ERR_INVALID_ARGUMENTS     = 698; //参数无效
  NET_QOS_ERROR                     = 699; //Qos 错误
  NET_QOS_OK                        = 700; //没有错误

implementation

end.
